// Code generated by MockGen. DO NOT EDIT.
// Source: mysqlclient.go

// Package mysql is a generated GoMock package.
package mysql

import (
	"taskmanager/zlog"
	"testing"

	"github.com/golang/mock/gomock"
	"github.com/stretchr/testify/assert"
)


func TestNewClient(t *testing.T) {
	mysqlclient := NewClient()
	assert.NotNil(t, mysqlclient)
}

func TestInit(t *testing.T) {
	zlog.InitLogger()
	defer zlog.Logger.Sync()
	var mysqlconfig MySQLConfig
	mysqlconfig.IP = "127.0.0.1"
	mysqlclient := NewClient()
	mysqlclient.Init(mysqlconfig)
}

func TestExec(t *testing.T) {
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mysqlclient := NewMockMySQLClient(ctrl)
	mysqlclient.EXPECT().Init(gomock.Any()).DoAndReturn(MockMySQLClient{}).AnyTimes()
	mysqlclient.EXPECT().Exec(gomock.Any().String(), gomock.All()).Return(int64(0), nil)

	var mysqlconfig MySQLConfig
	mysqlclient.Init(mysqlconfig)

	mysqlclient.Exec("", nil)
}
